AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Germain CAIJO - Exercice 1  

Parameters:
  # Paramètre pour identifier l’environnement (dev, test, prod)
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev/test/prod)

  # Préfixe du nom du bucket S3
  BucketNamePrefix:
    Type: String
    Default: bigdata-bucket
    Description: Prefix for S3 bucket

  # Nom de la table DynamoDB
  DynamoTableName:
    Type: String
    Default: BigDataTable
    Description: DynamoDB table name

  # Nom d’une paire de clés EC2 existante pour se connecter en SSH
  EC2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

  # Type d’instance EC2 (modifiable selon les besoins)
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  # AMI Amazon Linux 2023 (via SSM Parameter Store)
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2023-ami-kernel-default-x86_64
    Description: Latest Amazon Linux 2023 AMI

Resources:

  # -------------------------------
  # S3 Bucket pour stocker les fichiers
  # -------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${Environment}-${AWS::Region}"

  # -------------------------------
  # Table DynamoDB pour stocker des données structurées
  # -------------------------------
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: pk   # Partition Key
          AttributeType: S
        - AttributeName: sk   # Sort Key
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST  # Pas besoin de provisionner la capacité

  # -------------------------------
  # IAM Role pour l’instance EC2
  # Autorise l’accès à S3 et DynamoDB
  # -------------------------------
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:     # Autorise EC2 à assumer ce rôle
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:            # Politiques IAM attachées
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  # Profil d’instance (nécessaire pour associer le rôle à EC2)
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
      Path: "/"

  # -------------------------------
  # Security Group pour EC2
  # Autorise uniquement SSH depuis Internet (port 22)
  # -------------------------------
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # ⚠️ à restreindre à votre IP pour plus de sécurité

  # -------------------------------
  # Instance EC2
  # - Installe CloudWatch Agent et jq
  # - Écrit un fichier de test dans S3
  # - Ajoute un item dans DynamoDB
  # -------------------------------
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref EC2KeyName
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref LatestAmiId
      UserData:
        Fn::Base64: !Join
          - ''
          - - "#!/bin/bash\n"
            - "set -eux\n"
            - "dnf update -y\n"
            - "dnf install -y amazon-cloudwatch-agent jq\n"
            # Crée un fichier texte avec un message incluant l’environnement et la région
            - "echo \"hello from $(hostname) in "
            - !Ref AWS::Region
            - " ("
            - !Ref Environment
            - ")\" > /tmp/hello.txt\n"
            # Copie le fichier vers le bucket S3
            - "aws s3 cp /tmp/hello.txt s3://"
            - !Sub "${BucketNamePrefix}-${Environment}-${AWS::Region}"
            - "/hello.txt\n"
            # Récupère l’ID de l’instance depuis l’instance metadata
            - "INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)\n"
            # Insère un item dans DynamoDB avec l’ID de l’instance
            - "aws dynamodb put-item --table-name "
            - !Ref DynamoTableName
            - " --item '{\"pk\":{\"S\":\"host#'$INSTANCE_ID'\"},\"sk\":{\"S\":\"hello#'$(date +%s)'\"},\"msg\":{\"S\":\"hello from EC2\"}}'\n"
